preprocessing:
  atom_features:
  - atom_symbol
  - num_heavy_atoms
  - total_num_Hs
  - explicit_valence
  - is_aromatic
  - is_in_ring
  - formal_charge
  - hybridization_type
  dataset: PDBbind_combined
  dataset_csv: data/PDBBind/PDBbind_combined_casf_split_preprocessed.csv
  external_graph:
    path: data/PDBBind/PDBbind_combined_crystal_PLIG_6A_std.pickle
    use: true
  fingerprints:
    FP_path: None
    special_ECIF: false
    use_ECFP1024: false
    use_ECFP512: false
    use_ECIF: false
    use_FCFP1024: false
    use_FCFP512: false
    use_MAPR: false
  protein:
    max_seq_len: 1000
    protein_processing_type: no_protein
    seq_voc: ABCDEFGHIKLMNOPQRSTUVWXYZ
  use_graph: true
training:
  dataset: PDBbind_combined
  model: GATNet_PLIG_no_p
  params:
    LR: 0.0008
    log_interval: 10
    metric: pearson_correlation
    n_epochs: 16
    test_batch_size: 64
    train_batch_size: 64
  path_model_to_load: None
pure_prediction:
  dataset: PDBbind_combined
  old_path_to_model: ./output/trained_models/example_model/20211201-152343_model_GATNet_PLIG_no_p_6A_10_PDBbind_combined.model # This is the location of the model with pre-trained weights you want to load in
  path_to_model: ./GATNet.model
  model_name: GATNet_PLIG_no_p
  test_batch_size: 64